require("artem.plugins-setup")
require("artem.core.options")
require("artem.core.keymaps")
require("artem.core.colorscheme")
require("artem.plugins.comment")
require("artem.plugins.nvim-tree")
--require("artem.plugins.lualine")
--require("artem.plugins.telescope")
--require("artem.plugins.nvim-cmp")
--require("artem.plugins.lsp.mason")
--require("artem.plugins.lsp.lspsaga")
--require("artem.plugins.lsp.lspconfig")
--require("artem.plugins.lsp.null-ls")
--require("artem.plugins.autopairs")
--require("artem.plugins.treesitter")

